# Generated by Django 4.1.4 on 2022-12-18 11:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(default=api.models.random_card_number, editable=False, max_length=13),
        ),
    ]
